apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: zap
  name: zap-pvc
  namespace: zap-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: dynamic-slrs-blob-fuse



--- ## Mender MongoDB EFS ## ----

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/name: zap
  name: zap-pv
  namespace: zap-demo
spec:
  storageClassName: dynamic-slrs-blob-fuse
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0dad7a0e4a43fe6de::fsap-08acace089520bd22
    volumeAttributes:
      encryptInTransit: "false" 