apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: zap-demo
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfod
        image: 593518286265.dkr.ecr.us-east-1.amazonaws.com/stefanprodan/podinfo:6.7.0
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --level=info