{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "appmesh-prometheus.serviceAccountName" . }}
  labels:
{{ include "appmesh-prometheus.labels" . | indent 4 }}
{{- end }}
