apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager


---

kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled



---

apiVersion: v1
kind: Namespace
metadata:
  name: zap-demo
  labels:
    aws-observability: enabled
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled


---

apiVersion: v1
kind: Namespace
metadata:
  name: appmesh-system
  labels:
    aws-observability: enabled
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled


    