apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources: 
  - ../../base/kube-system/


generatorOptions:
 disableNameSuffixHash: true

helmGlobals:
  chartHome: ../../charts

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  valuesFile: ./cert-manager.yaml
  includeCRDs: false
  version: v1.18.2

- name: aws-load-balancer-controller
  releaseName: aws-load-balancer-controller
  namespace: kube-system
  valuesFile:  ./aws-load-balancer-controller.yaml
  includeCRDs: false
  version: v2.13.3

- name: metrics-server
  releaseName: metrics-server
  namespace: kube-system
  valuesFile:  ./metrics-server.yaml
  includeCRDs: false
  version: 0.8.0