name: Get Node Group Size

on:
  workflow_dispatch:

jobs:
  check-nodegroup:
    name: Get Number of Running Nodes
    runs-on: ubuntu-latest
    outputs:
      node_count: ${{ steps.extract.outputs.NODE_COUNT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get Node Group Size
        run: |
          COUNT=$(aws eks describe-nodegroup \
            --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
            --nodegroup-name ${{ secrets.EKS_NODEGROUP_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --query "nodegroup.scalingConfig.desiredSize" \
            --output text)

          echo "::notice title=NODES::$COUNT"
          
