name: Mirror EKS Controller Images to ECR

on:
  workflow_dispatch:

jobs:
  mirror:
    name: Mirror EKS Controller Images to ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ACCOUNT: ${{ secrets.ACCOUNT }}

      IMAGE_GROUPS: "CERT_MANAGER LOAD_BALANCER SWAGGER_UI METRICS_SERVER APPMESH_CONTROLLER AWS_APPMESH_ENVOY AWS_XRAY_DAEMON PROM_PROMETHEUS FLUXCD_FLAGGER"
      #IMAGE_GROUPS: "CERT_MANAGER LOAD_BALANCER SWAGGER_UI METRICS_SERVER APPMESH_CONTROLLER AWS_APPMESH_ENVOY AWS_APPMESH_PROXY_ROUTE_MANAGER AWS_XRAY_DAEMON"

      CERT_MANAGER_TAG: "v1.18.2"
      CERT_MANAGER_ECR_MAP: |
        {
          "quay.io/jetstack/cert-manager-startupapicheck": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/corbie-cert-manager/startupapicheck",
          "quay.io/jetstack/cert-manager-acmesolver": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/corbie-cert-manager/acmesolver",
          "quay.io/jetstack/cert-manager-cainjector": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/corbie-cert-manager/cainjector",
          "quay.io/jetstack/cert-manager-controller": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/corbie-cert-manager/controller",
          "quay.io/jetstack/cert-manager-webhook": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/corbie-cert-manager/webhook"
        }

      LOAD_BALANCER_TAG: "v2.13.3"
      LOAD_BALANCER_ECR_MAP: |
        {
          "public.ecr.aws/eks/aws-load-balancer-controller": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/corbie-lb-eks"
        }

      SWAGGER_UI_TAG: "v5.27.1"
      SWAGGER_UI_ECR_MAP: |
        {
          "docker.swagger.io/swaggerapi/swagger-ui": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/swaggerapi/swagger-ui"
        }

      METRICS_SERVER_TAG: "0.8.0-debian-12-r1"
      METRICS_SERVER_ECR_MAP: |
        {
          "docker.io/bitnami/metrics-server": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/bitnami/metrics-server"
        }

    
      APPMESH_CONTROLLER_TAG: "v1.13.1"
      APPMESH_CONTROLLER_ECR_MAP: |
        {
          "public.ecr.aws/appmesh/appmesh-controller": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/amazon/appmesh-controller"
        }



      AWS_APPMESH_ENVOY_TAG: "v1.29.6.0-prod"
      AWS_APPMESH_ENVOY_ECR_MAP: |
        {
          "public.ecr.aws/appmesh/aws-appmesh-envoy": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy"
        }


      AWS_XRAY_DAEMON_TAG: "latest"
      AWS_XRAY_DAEMON_ECR_MAP: |
        {
          "public.ecr.aws/xray/aws-xray-daemon": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/xray/aws-xray-daemon"
        }

      PROM_PROMETHEUS_TAG: "v2.13.1"
      PROM_PROMETHEUS_ECR_MAP: |
        {
          "docker.io/prom/prometheus": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/prom/prometheus"
        }


      FLUXCD_FLAGGER_TAG: "1.41.0"
      FLUXCD_FLAGGER__ECR_MAP: |
        {
          "ghcr.io/fluxcd/flagger": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/fluxcd/flagger"
        }

      # AWS_APPMESH_PROXY_ROUTE_MANAGER_TAG: "v7-prod"
      # AWS_APPMESH_PROXY_ROUTE_MANAGER_ECR_MAP: |
      #   {
      #     "public.ecr.aws/appmesh/aws-appmesh-proxy-route-manager": "${ACCOUNT}.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-proxy-route-manager"
      #   }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Mirror images from IMAGE_GROUPS
        run: |
          set -euo pipefail

          for GROUP in $IMAGE_GROUPS; do
            TAG_VAR="${GROUP}_TAG"
            MAP_VAR="${GROUP}_ECR_MAP"

            TAG="${!TAG_VAR}"
            RAW_MAP="${!MAP_VAR}"

            MAP=$(echo "$RAW_MAP" | envsubst)

            echo "Processing group: $GROUP"
            echo "Using tag: $TAG"

            # Reset image map
            unset IMAGES || true
            declare -A IMAGES

            while IFS="=" read -r src dst; do
              src_clean="$(echo "$src" | xargs)"
              dst_clean="$(echo "$dst" | xargs)"
              IMAGES["$src_clean"]="$dst_clean"
            done < <(echo "$MAP" | jq -r 'to_entries[] | "\(.key)=\(.value)"')

            for SRC_IMAGE in "${!IMAGES[@]}"; do
              DST_IMAGE="${IMAGES[$SRC_IMAGE]}"
              
              echo "Checking availability of $SRC_IMAGE:$TAG"
              if ! docker manifest inspect "$SRC_IMAGE:$TAG" > /dev/null 2>&1; then
                echo "Image not found: $SRC_IMAGE:$TAG — skipping"
                continue
              fi

              echo "Pulling $SRC_IMAGE:$TAG"
              docker pull "$SRC_IMAGE:$TAG"

              echo "Tagging $DST_IMAGE:$TAG"
              docker tag "$SRC_IMAGE:$TAG" "$DST_IMAGE:$TAG"

              echo "Pushing $DST_IMAGE:$TAG"
              docker push "$DST_IMAGE:$TAG"
            done

            echo "Finished group: $GROUP"
            echo ""
          done
