name: Scale Up Mender Namespace and Node Group

on:
  workflow_dispatch:

jobs:
  scale-up:
    name: Scale Up Deployments, StatefulSets & Node Group
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Scale Node Group back to 8
        run: |
          aws eks update-nodegroup-config \
            --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
            --nodegroup-name ${{ secrets.EKS_NODEGROUP_NAME }} \
            --scaling-config minSize=6,maxSize=10,desiredSize=8

      - name: Scale Deployments back up
        run: |
          declare -A DEPLOYMENTS=(
            [mender-api-gateway]=1
            [mender-create-artifact-worker]=1
            [mender-deployments]=1
            [mender-device-auth]=1
            [mender-deviceconfig]=1
            [mender-deviceconnect]=1
            [mender-gui]=1
            [mender-inventory]=1
            [mender-iot-manager]=1
            [mender-useradm]=1
            [mender-workflows-server]=1
            [mender-workflows-worker]=1
            [mongodb]=1
            [nats-box]=1
          )
          for d in "${!DEPLOYMENTS[@]}"; do
            echo "Scaling deployment $d to ${DEPLOYMENTS[$d]}"
            kubectl scale deployment $d -n mender --replicas=${DEPLOYMENTS[$d]} || true
          done

      - name: Scale StatefulSets back up
        run: |
          declare -A STATEFULSETS=(
            [nats]=1
            [redis-master]=1
            [redis-replicas]=3
          )
          for s in "${!STATEFULSETS[@]}"; do
            echo "Scaling statefulset $s to ${STATEFULSETS[$s]}"
            kubectl scale statefulset $s -n mender --replicas=${STATEFULSETS[$s]} || true
          done
