# Default values for appmesh-grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 1XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/grafana/grafana
  tag: 6.4.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

namespace: appmesh-system
service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  # serviceAccount.create: Whether to create a service account or not
  create: false
  # serviceAccount.name: The name of the service account to create or use
  name: "zap-sa"

rbac:
  # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
  pspEnabled: false

# Prometheus URL
url: http://appmesh-prometheus.appmesh-system.svc.cluster.local:9090
