apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appmesh-prometheus
  namespace: appmesh-system
  annotations:
    # ALB config
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: zap-sec
    alb.ingress.kubernetes.io/subnets: subnet-0XXXXXXXXXXXXXX,subnet-0XXXXXXXXXXXXXX,subnet-00XXXXXXXXXXXXXX
    # TLS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:1XXXXXXXXXX:certificate/XxXxXxX-XxXxXxX-XxXxXxX-XxXxXxX
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    # Health check
    alb.ingress.kubernetes.io/healthcheck-path: /-/healthy
spec:
  ingressClassName: alb
  rules:
  - host: zap-prometheus.sec.zaptechnology.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: appmesh-prometheus
            port:
              number: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appmesh-grafana
  namespace: appmesh-system
  annotations:
    # ALB config
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: zap-sec
    alb.ingress.kubernetes.io/subnets: subnet-0XXXXXXXXXXXXXX,subnet-0XXXXXXXXXXXXXX,subnet-00XXXXXXXXXXXXXX
    # TLS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:1XXXXXXXXXX:certificate/XxXxXxX-XxXxXxX-XxXxXxX-XxXxXxX
    # Health check (Grafana)
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  ingressClassName: alb
  rules:
  - host: zap-grafana.sec.zaptechnology.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: appmesh-grafanac   # <- fixed
            port:
              number: 3000


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appmesh-gateway
  namespace: appmesh-system
  annotations:
    # ALB config
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: zap-sec
    alb.ingress.kubernetes.io/subnets: subnet-0XXXXXXXXXXXXXX,subnet-0XXXXXXXXXXXXXX,subnet-00XXXXXXXXXXXXXX
    # TLS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:1XXXXXXXXXX:certificate/XxXxXxX-XxXxXxX-XxXxXxX-XxXxXxX
    # Health check (Grafana)
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  ingressClassName: alb
  rules:
  - host: zap-gateway.sec.zaptechnology.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: appmesh-gateway   # <- fixed
            port:
              number: 80
