apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources: 
  - ../../../base/controllers/
  - loadtester-sa.yaml

generatorOptions:
 disableNameSuffixHash: true

helmGlobals:
  chartHome: ../../../charts

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  valuesFile: ./cert-manager.yaml
  includeCRDs: false
  version: v1.18.2

- name: aws-load-balancer-controller
  releaseName: aws-load-balancer-controller
  namespace: kube-system
  valuesFile:  ./aws-load-balancer-controller.yaml
  includeCRDs: false
  version: v2.13.3

- name: loadtester
  releaseName: loadtester
  namespace: zap-demo
  valuesFile:  ./flagger-loadtester.yaml
  includeCRDs: false
  version: 0.35.0

- name: metrics-server
  releaseName: metrics-server
  namespace: kube-system
  valuesFile:  ./metrics-server.yaml
  includeCRDs: false
  version: 0.8.0


- name: appmesh-controller
  releaseName: appmesh-controller
  namespace: appmesh-system
  valuesFile:  ./appmesh-system.yaml
  includeCRDs: false
  version: 1.13.1


- name: appmesh-prometheus
  releaseName: appmesh-prometheus
  namespace: appmesh-system
  valuesFile:  ./appmesh-prometheus.yaml
  includeCRDs: false
  version: 2.13.1
  